name: Build and push api docker image

on: 
  push:
    branches : [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-api:
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: "./Dockerfile.api"
      image_name: ${{ github.repository }}-api
    # registry_username and registry_api_key must be defined
    secrets: inherit
