name: Build and push and deploy vote.eirb.fr containers

on: 
  push:
    branches : [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-api:
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: "./Dockerfile.api"
      image_name: ${{ github.repository }}-api
    # registry_username and registry_api_key must be defined
    secrets: inherit

  build-and-push-db:
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: "./Dockerfile.database"
      image_name: ${{ github.repository }}-db
    # registry_username and registry_api_key must be defined
    secrets: inherit

  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Creates the .env file and puts the required text in it
        env:
          STORE_PORT: ${{ vars.STORE_PORT }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
        run: |
          echo "STORE_PORT=$STORE_PORT" > ${{ github.workspace }}/.env
          echo "VITE_API_URL=$VITE_API_URL" >> ${{ github.workspace }}/.env
      - name: Upload the .env file
        uses: actions/upload-artifact@v4
        with:
          name: env_file
          path: ${{ github.workspace }}/.env
          include-hidden-files: true

  build-and-push-www:
    needs: create-env
    uses: Eirbware/.github/.github/workflows/build-and-publish.yml@master
    with:
      file: "./Dockerfile.www"
      image_name: ${{ github.repository }}-www
      artifact_name: env_file
    # registry_username and registry_api_key must be defined
    secrets: inherit

  deploy:
    needs: [ build-and-push-www, build-and-push-db, build-and-push-api ]
    uses: Eirbware/.github/.github/workflows/deploy-stack@master
    # portainer_stack_webhook must be defined
    secrets: inherit
